---
# Source: rbac-manager/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rbac-manager
  labels:
    app: rbac-manager
    chart: rbac-manager-1.4.2
    release: rbac-manager
    heritage: Tiller

---
# Source: rbac-manager/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbac-manager
  labels:
    app: rbac-manager
    chart: rbac-manager-1.4.2
    release: rbac-manager
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rbac-manager
      release: rbac-manager
  template:
    metadata:
      labels:
        app: rbac-manager
        release: rbac-manager 
    spec:
      serviceAccountName: rbac-manager
      containers:
      - name: rbac-manager
        image: "quay.io/reactiveops/rbac-manager:0.8.4"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /metrics
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /metrics
            port: 8080
        securityContext:
          runAsUser: 1200
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
        ports:
          # metrics port
          - name: http-metrics
            containerPort: 8080
            protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
          

